// <auto-generated />
using System;
using ElectricERP.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElectricERP.Infrastructure.Migrations
{
    [DbContext(typeof(ElectricERPDbContext))]
    [Migration("20260924194800_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ElectricERP.Infrastructure.Entities.Alerta", b =>
                {
                    b.Property<int>("IdAlerta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAlerta"));

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaHora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdStock")
                        .HasColumnType("int");

                    b.Property<string>("TipoAlerta")
                        .IsRequired()
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)");

                    b.HasKey("IdAlerta");

                    b.HasIndex("IdStock");

                    b.ToTable("Alerta", null, t =>
                        {
                            t.HasCheckConstraint("CK_Alerta_Tipo", "[TipoAlerta] IN ('MINIMO','MAXIMO')");
                        });
                });

            modelBuilder.Entity("ElectricERP.Infrastructure.Entities.Almacen", b =>
                {
                    b.Property<int>("IdAlmacen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAlmacen"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("FechaAlta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdAlmacen");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("UQ_Almacen_Nombre");

                    b.ToTable("Almacen", null, t =>
                        {
                            t.HasCheckConstraint("CK_Almacen_Direccion", "LEN([Direccion]) > 7");

                            t.HasCheckConstraint("CK_Almacen_Nombre", "LEN([Nombre]) > 4");
                        });
                });

            modelBuilder.Entity("ElectricERP.Infrastructure.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshTokenHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ElectricERP.Infrastructure.Entities.DetalleInventario", b =>
                {
                    b.Property<int>("IdDetalleInventario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalleInventario"));

                    b.Property<int>("CantidadInventario")
                        .HasColumnType("int");

                    b.Property<int>("IdInventario")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.HasKey("IdDetalleInventario");

                    b.HasIndex("IdInventario");

                    b.HasIndex("IdProducto");

                    b.ToTable("DetalleInventario", null, t =>
                        {
                            t.HasCheckConstraint("CK_DetalleInventario_Cantidad", "[CantidadInventario] >= 0");
                        });
                });

            modelBuilder.Entity("ElectricERP.Infrastructure.Entities.DetalleTransferencia", b =>
                {
                    b.Property<int>("IdDetalleTransferencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalleTransferencia"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<int>("IdTransferencia")
                        .HasColumnType("int");

                    b.HasKey("IdDetalleTransferencia");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdTransferencia");

                    b.ToTable("DetalleTransferencia", null, t =>
                        {
                            t.HasCheckConstraint("CK_DetalleTransferencia_Cantidad", "[Cantidad] > 0");
                        });
                });

            modelBuilder.Entity("ElectricERP.Infrastructure.Entities.Etiqueta", b =>
                {
                    b.Property<int>("IdEtiqueta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEtiqueta"));

                    b.Property<string>("CodigoQr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("CodigoQr");

                    b.Property<DateTime>("FechaAlta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.HasKey("IdEtiqueta");

                    b.HasIndex("CodigoQr")
                        .IsUnique()
                        .HasDatabaseName("UQ_Etiqueta_Codigo");

                    b.HasIndex("IdProducto");

                    b.ToTable("Etiqueta", null, t =>
                        {
                            t.HasCheckConstraint("CK_Etiqueta_CodigoQr", "LEN([CodigoQr]) > 5");
                        });
                });

            modelBuilder.Entity("ElectricERP.Infrastructure.Entities.Inventario", b =>
                {
                    b.Property<int>("IdInventario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInventario"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("FechaAlta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdSeccion")
                        .HasColumnType("int");

                    b.HasKey("IdInventario");

                    b.HasIndex("IdSeccion");

                    b.ToTable("Inventario", null, t =>
                        {
                            t.HasCheckConstraint("CK_Inventario_Estado", "[Estado] IN ('ABIERTO','FINALIZADO')");

                            t.HasCheckConstraint("CK_Inventario_Fechas", "[FechaCierre] IS NULL OR [FechaCierre] > [FechaAlta]");
                        });
                });

            modelBuilder.Entity("ElectricERP.Infrastructure.Entities.Movimiento", b =>
                {
                    b.Property<long>("IdMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdMovimiento"));

                    b.Property<int>("CantidadUnidades")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("FechaHora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<int>("IdSeccion")
                        .HasColumnType("int");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("ValorAnterior")
                        .HasColumnType("int");

                    b.Property<int>("ValorPosterior")
                        .HasColumnType("int");

                    b.HasKey("IdMovimiento");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdSeccion");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Movimiento", null, t =>
                        {
                            t.HasCheckConstraint("CK_Movimiento_Cantidad", "[CantidadUnidades] > 0");

                            t.HasCheckConstraint("CK_Movimiento_Resultado", "[Resultado] IN ('EXITOSO','FALLIDO')");

                            t.HasCheckConstraint("CK_Movimiento_TipoMovimiento", "[TipoMovimiento] IN ('INGRESO','EGRESO','TRANSFERENCIA','AJUSTE_STOCK')");
                        });
                });

            modelBuilder.Entity("ElectricERP.Infrastructure.Entities.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProducto"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("CodigoSku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CodigoSKU");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdProducto");

                    b.HasIndex("CodigoSku")
                        .IsUnique()
                        .HasDatabaseName("UQ_Producto_SKU");

                    b.HasIndex("IdProveedor");

                    b.ToTable("Producto", null, t =>
                        {
                            t.HasCheckConstraint("CK_Producto_Categoria", "[Categoria] IN ('Resistencias','Capacitores','Inductores','Diodos','Transistores','Circuitos','Integrados','Sensores','Conectores','Cables','Fuentes de Alimentacion','Reles','Fusibles','Herramientas','Accesorios')");

                            t.HasCheckConstraint("CK_Producto_CodigoSKU", "LEN([CodigoSKU]) > 10 AND [CodigoSKU] NOT LIKE '%[^A-Z0-9]%' AND [CodigoSKU] LIKE '%[A-Z]%' AND [CodigoSKU] LIKE '%[0-9]%'");

                            t.HasCheckConstraint("CK_Producto_Descripcion", "[Descripcion] IS NULL OR LEN([Descripcion]) > 1");

                            t.HasCheckConstraint("CK_Producto_Nombre", "LEN([Nombre]) > 3");

                            t.HasCheckConstraint("CK_Producto_UnidadMedida", "[UnidadMedida] IN ('m','cm','kg','Consumo Electrico')");
                        });
                });

            modelBuilder.Entity("ElectricERP.Infrastructure.Entities.Proveedor", b =>
                {
                    b.Property<int>("IdProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProveedor"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(75)
                        .IsUnicode(false)
                        .HasColumnType("varchar(75)");

                    b.Property<string>("Rut")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.HasKey("IdProveedor");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_Proveedor_Mail")
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("Rut")
                        .IsUnique()
                        .HasDatabaseName("UQ_Proveedor_Rut");

                    b.ToTable("Proveedor", null, t =>
                        {
                            t.HasCheckConstraint("CK_Proveedor_Direccion", "LEN([Direccion]) > 7");

                            t.HasCheckConstraint("CK_Proveedor_Email", "[Email] IS NULL OR (LEN([Email]) > 7 AND [Email] LIKE '%_@_%_.%' AND [Email] NOT LIKE '% %' AND [Email] NOT LIKE '%..%' AND [Email] NOT LIKE '%@%@%' AND [Email] NOT LIKE '%.@' AND [Email] NOT LIKE '@%' AND [Email] NOT LIKE '%.')");

                            t.HasCheckConstraint("CK_Proveedor_Nombre", "LEN([Nombre]) > 3");

                            t.HasCheckConstraint("CK_Proveedor_Rut", "LEN([Rut]) = 11 AND [Rut] LIKE '21%' AND [Rut] NOT LIKE '%[^0-9]%'");

                            t.HasCheckConstraint("CK_Proveedor_Telefono", "[Telefono] IS NULL OR (LEN([Telefono]) > 7 AND [Telefono] NOT LIKE '%[^0-9]%')");
                        });
                });

            modelBuilder.Entity("ElectricERP.Infrastructure.Entities.Seccion", b =>
                {
                    b.Property<int>("IdSeccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSeccion"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<int>("IdAlmacen")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdSeccion");

                    b.HasIndex("IdAlmacen", "Nombre")
                        .IsUnique()
                        .HasDatabaseName("UQ_Seccion");

                    b.ToTable("Seccion", null, t =>
                        {
                            t.HasCheckConstraint("CK_Seccion_Descripcion", "[Descripcion] IS NULL OR LEN([Descripcion]) > 1");

                            t.HasCheckConstraint("CK_Seccion_Nombre", "LEN([Nombre]) > 3");
                        });
                });

            modelBuilder.Entity("ElectricERP.Infrastructure.Entities.SolicitudAjuste", b =>
                {
                    b.Property<int>("IdSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSolicitud"));

                    b.Property<int>("CantidadSolicitada")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("IdEmpleadoSolicitante")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<string>("IdSupervisorResolutor")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("IdSolicitud");

                    b.HasIndex("IdEmpleadoSolicitante");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdSupervisorResolutor");

                    b.ToTable("SolicitudAjuste", null, t =>
                        {
                            t.HasCheckConstraint("CK_Ajuste_CantidadSolicitada", "[CantidadSolicitada] >= 0");

                            t.HasCheckConstraint("CK_Ajuste_Estado", "[Estado] IN ('PENDIENTE','APROBADO','RECHAZADO')");

                            t.HasCheckConstraint("CK_Ajuste_FechaResolucion", "[FechaResolucion] > [FechaSolicitud]");

                            t.HasCheckConstraint("CK_Ajuste_Motivo", "LEN([Motivo]) > 1");

                            t.HasCheckConstraint("CK_Ajuste_Tipo", "[Tipo] IN ('STOCK','INVENTARIO')");
                        });
                });

            modelBuilder.Entity("ElectricERP.Infrastructure.Entities.Stock", b =>
                {
                    b.Property<int>("IdStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStock"));

                    b.Property<int>("CantidadActual")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<int>("IdSeccion")
                        .HasColumnType("int");

                    b.Property<int>("Maximo")
                        .HasColumnType("int");

                    b.Property<int>("Minimo")
                        .HasColumnType("int");

                    b.Property<DateTime>("UltimaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("IdStock");

                    b.HasIndex("IdSeccion");

                    b.HasIndex("IdProducto", "IdSeccion")
                        .IsUnique()
                        .HasDatabaseName("UQ_Stock");

                    b.ToTable("Stock", null, t =>
                        {
                            t.HasCheckConstraint("CK_Stock_Cantidad", "[CantidadActual] >= 0 AND [CantidadActual] < 1999");

                            t.HasCheckConstraint("CK_Stock_Maximo", "[Maximo] > [Minimo]");

                            t.HasCheckConstraint("CK_Stock_Minimo", "[Minimo] >= 0");
                        });
                });

            modelBuilder.Entity("ElectricERP.Infrastructure.Entities.Transferencia", b =>
                {
                    b.Property<int>("IdTransferencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTransferencia"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("FechaAutorizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEjecucion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("IdAdministradorAutorizador")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("IdAlmacenDestino")
                        .HasColumnType("int");

                    b.Property<int>("IdAlmacenOrigen")
                        .HasColumnType("int");

                    b.Property<string>("IdSupervisorSolicitante")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdTransportista")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("IdVehiculo")
                        .HasColumnType("int");

                    b.HasKey("IdTransferencia");

                    b.HasIndex("IdAdministradorAutorizador");

                    b.HasIndex("IdAlmacenDestino");

                    b.HasIndex("IdAlmacenOrigen");

                    b.HasIndex("IdSupervisorSolicitante");

                    b.HasIndex("IdTransportista");

                    b.HasIndex("IdVehiculo");

                    b.ToTable("Transferencia", null, t =>
                        {
                            t.HasCheckConstraint("CK_Transferencia_Almacenes", "[IdAlmacenOrigen] <> [IdAlmacenDestino]");

                            t.HasCheckConstraint("CK_Transferencia_Estado", "[Estado] IN ('PENDIENTE','AUTORIZADA','ASIGNADA','EN_TRANSITO','ENTREGADA','FINALIZADA','RECHAZADA')");

                            t.HasCheckConstraint("CK_Transferencia_FechaAutorizacion", "[FechaAutorizacion] IS NULL OR [FechaAutorizacion] > [FechaSolicitud]");

                            t.HasCheckConstraint("CK_Transferencia_FechaEjecucion", "[FechaEjecucion] IS NULL OR [FechaEjecucion] > [FechaAutorizacion]");

                            t.HasCheckConstraint("CK_Transferencia_FechaEntrega", "[FechaEntrega] IS NULL OR [FechaEntrega] > [FechaEjecucion]");
                        });
                });

            modelBuilder.Entity("ElectricERP.Infrastructure.Entities.UbicacionGps", b =>
                {
                    b.Property<int>("IdUbicacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUbicacion"));

                    b.Property<DateTime>("FechaHora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("IdTransportista")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Latitud")
                        .HasColumnType("decimal(10, 8)");

                    b.Property<decimal>("Longitud")
                        .HasColumnType("decimal(11, 8)");

                    b.HasKey("IdUbicacion");

                    b.HasIndex("IdTransportista");

                    b.ToTable("UbicacionGPS", null, t =>
                        {
                            t.HasCheckConstraint("CK_UbicacionGPS_Latitud", "[Latitud] BETWEEN -90 AND 90");

                            t.HasCheckConstraint("CK_UbicacionGPS_Longitud", "[Longitud] BETWEEN -180 AND 180");
                        });
                });

            modelBuilder.Entity("ElectricERP.Infrastructure.Entities.Vehiculo", b =>
                {
                    b.Property<int>("IdVehiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVehiculo"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("CapacidadCarga")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("IdVehiculo");

                    b.HasIndex("Matricula")
                        .IsUnique()
                        .HasDatabaseName("UQ_Vehiculo_Matricula");

                    b.ToTable("Vehiculo", null, t =>
                        {
                            t.HasCheckConstraint("CK_Vehiculo_Carga", "[CapacidadCarga] > 0");

                            t.HasCheckConstraint("CK_Vehiculo_Marca", "LEN([Marca]) > 3");

                            t.HasCheckConstraint("CK_Vehiculo_Matricula", "LEN([Matricula]) = 8 AND [Matricula] LIKE '[A-Z][A-Z][A-Z] [0-9][0-9][0-9][0-9]'");

                            t.HasCheckConstraint("CK_Vehiculo_Modelo", "LEN([Modelo]) > 3");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ElectricERP.Infrastructure.Entities.Alerta", b =>
                {
                    b.HasOne("ElectricERP.Infrastructure.Entities.Stock", "IdStockNavigation")
                        .WithMany("Alerta")
                        .HasForeignKey("IdStock")
                        .IsRequired()
                        .HasConstraintName("FK_Alerta_Stock");

                    b.Navigation("IdStockNavigation");
                });

            modelBuilder.Entity("ElectricERP.Infrastructure.Entities.DetalleInventario", b =>
                {
                    b.HasOne("ElectricERP.Infrastructure.Entities.Inventario", "IdInventarioNavigation")
                        .WithMany("DetalleInventarios")
                        .HasForeignKey("IdInventario")
                        .IsRequired()
                        .HasConstraintName("FK_DetalleInventario_Inventario");

                    b.HasOne("ElectricERP.Infrastructure.Entities.Producto", "IdProductoNavigation")
                        .WithMany("DetalleInventarios")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("FK_DetalleInventario_Producto");

                    b.Navigation("IdInventarioNavigation");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("ElectricERP.Infrastructure.Entities.DetalleTransferencia", b =>
                {
                    b.HasOne("ElectricERP.Infrastructure.Entities.Producto", "IdProductoNavigation")
                        .WithMany("DetalleTransferencia")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("FK_DetalleTransferencia_Producto");

                    b.HasOne("ElectricERP.Infrastructure.Entities.Transferencia", "IdTransferenciaNavigation")
                        .WithMany("DetalleTransferencia")
                        .HasForeignKey("IdTransferencia")
                        .IsRequired()
                        .HasConstraintName("FK_DetalleTransferencia_Transferencia");

                    b.Navigation("IdProductoNavigation");

                    b.Navigation("IdTransferenciaNavigation");
                });

            modelBuilder.Entity("ElectricERP.Infrastructure.Entities.Etiqueta", b =>
                {
                    b.HasOne("ElectricERP.Infrastructure.Entities.Producto", "IdProductoNavigation")
                        .WithMany("Etiqueta")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("FK_Etiqueta_Producto");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("ElectricERP.Infrastructure.Entities.Inventario", b =>
                {
                    b.HasOne("ElectricERP.Infrastructure.Entities.Seccion", "IdSeccionNavigation")
                        .WithMany("Inventarios")
                        .HasForeignKey("IdSeccion")
                        .IsRequired()
                        .HasConstraintName("FK_Inventario_Seccion");

                    b.Navigation("IdSeccionNavigation");
                });

            modelBuilder.Entity("ElectricERP.Infrastructure.Entities.Movimiento", b =>
                {
                    b.HasOne("ElectricERP.Infrastructure.Entities.Producto", "IdProductoNavigation")
                        .WithMany("Movimientos")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("FK_Movimiento_Producto");

                    b.HasOne("ElectricERP.Infrastructure.Entities.Seccion", "IdSeccionNavigation")
                        .WithMany("Movimientos")
                        .HasForeignKey("IdSeccion")
                        .IsRequired()
                        .HasConstraintName("FK_Movimiento_Seccion");

                    b.HasOne("ElectricERP.Infrastructure.Entities.ApplicationUser", "IdUsuarioNavigation")
                        .WithMany("Movimientos")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_Movimiento_Usuario");

                    b.Navigation("IdProductoNavigation");

                    b.Navigation("IdSeccionNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("ElectricERP.Infrastructure.Entities.Producto", b =>
                {
                    b.HasOne("ElectricERP.Infrastructure.Entities.Proveedor", "IdProveedorNavigation")
                        .WithMany("Productos")
                        .HasForeignKey("IdProveedor")
                        .IsRequired()
                        .HasConstraintName("FK_Producto_Proveedor");

                    b.Navigation("IdProveedorNavigation");
                });

            modelBuilder.Entity("ElectricERP.Infrastructure.Entities.Seccion", b =>
                {
                    b.HasOne("ElectricERP.Infrastructure.Entities.Almacen", "IdAlmacenNavigation")
                        .WithMany("Secciones")
                        .HasForeignKey("IdAlmacen")
                        .IsRequired()
                        .HasConstraintName("FK_Seccion_Almacen");

                    b.Navigation("IdAlmacenNavigation");
                });

            modelBuilder.Entity("ElectricERP.Infrastructure.Entities.SolicitudAjuste", b =>
                {
                    b.HasOne("ElectricERP.Infrastructure.Entities.ApplicationUser", "IdEmpleadoSolicitanteNavigation")
                        .WithMany("SolicitudAjusteIdEmpleadoSolicitanteNavigations")
                        .HasForeignKey("IdEmpleadoSolicitante")
                        .IsRequired()
                        .HasConstraintName("FK_Ajuste_Empleado");

                    b.HasOne("ElectricERP.Infrastructure.Entities.Producto", "IdProductoNavigation")
                        .WithMany("SolicitudAjustes")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("FK_Ajuste_Producto");

                    b.HasOne("ElectricERP.Infrastructure.Entities.ApplicationUser", "IdSupervisorResolutorNavigation")
                        .WithMany("SolicitudAjusteIdSupervisorResolutorNavigations")
                        .HasForeignKey("IdSupervisorResolutor")
                        .HasConstraintName("FK_Ajuste_Supervisor");

                    b.Navigation("IdEmpleadoSolicitanteNavigation");

                    b.Navigation("IdProductoNavigation");

                    b.Navigation("IdSupervisorResolutorNavigation");
                });

            modelBuilder.Entity("ElectricERP.Infrastructure.Entities.Stock", b =>
                {
                    b.HasOne("ElectricERP.Infrastructure.Entities.Producto", "IdProductoNavigation")
                        .WithMany("Stocks")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("FK_Stock_Producto");

                    b.HasOne("ElectricERP.Infrastructure.Entities.Seccion", "IdSeccionNavigation")
                        .WithMany("Stocks")
                        .HasForeignKey("IdSeccion")
                        .IsRequired()
                        .HasConstraintName("FK_Stock_Seccion");

                    b.Navigation("IdProductoNavigation");

                    b.Navigation("IdSeccionNavigation");
                });

            modelBuilder.Entity("ElectricERP.Infrastructure.Entities.Transferencia", b =>
                {
                    b.HasOne("ElectricERP.Infrastructure.Entities.ApplicationUser", "IdAdministradorAutorizadorNavigation")
                        .WithMany("TransferenciaIdAdministradorAutorizadorNavigations")
                        .HasForeignKey("IdAdministradorAutorizador")
                        .HasConstraintName("FK_Transferencia_Admin");

                    b.HasOne("ElectricERP.Infrastructure.Entities.Almacen", "IdAlmacenDestinoNavigation")
                        .WithMany("TransferenciaIdAlmacenDestinoNavigations")
                        .HasForeignKey("IdAlmacenDestino")
                        .IsRequired()
                        .HasConstraintName("FK_Transferencia_Destino");

                    b.HasOne("ElectricERP.Infrastructure.Entities.Almacen", "IdAlmacenOrigenNavigation")
                        .WithMany("TransferenciaIdAlmacenOrigenNavigations")
                        .HasForeignKey("IdAlmacenOrigen")
                        .IsRequired()
                        .HasConstraintName("FK_Transferencia_Origen");

                    b.HasOne("ElectricERP.Infrastructure.Entities.ApplicationUser", "IdSupervisorSolicitanteNavigation")
                        .WithMany("TransferenciaIdSupervisorSolicitanteNavigations")
                        .HasForeignKey("IdSupervisorSolicitante")
                        .IsRequired()
                        .HasConstraintName("FK_Transferencia_Supervisor");

                    b.HasOne("ElectricERP.Infrastructure.Entities.ApplicationUser", "IdTransportistaNavigation")
                        .WithMany("TransferenciaIdTransportistaNavigations")
                        .HasForeignKey("IdTransportista")
                        .HasConstraintName("FK_Transferencia_Transportista");

                    b.HasOne("ElectricERP.Infrastructure.Entities.Vehiculo", "IdVehiculoNavigation")
                        .WithMany("Transferencia")
                        .HasForeignKey("IdVehiculo")
                        .HasConstraintName("FK_Transferencia_Vehiculo");

                    b.Navigation("IdAdministradorAutorizadorNavigation");

                    b.Navigation("IdAlmacenDestinoNavigation");

                    b.Navigation("IdAlmacenOrigenNavigation");

                    b.Navigation("IdSupervisorSolicitanteNavigation");

                    b.Navigation("IdTransportistaNavigation");

                    b.Navigation("IdVehiculoNavigation");
                });

            modelBuilder.Entity("ElectricERP.Infrastructure.Entities.UbicacionGps", b =>
                {
                    b.HasOne("ElectricERP.Infrastructure.Entities.ApplicationUser", "IdTransportistaNavigation")
                        .WithMany("UbicacionGps")
                        .HasForeignKey("IdTransportista")
                        .IsRequired()
                        .HasConstraintName("FK_UbicacionGPS_Transportista");

                    b.Navigation("IdTransportistaNavigation");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ElectricERP.Infrastructure.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ElectricERP.Infrastructure.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElectricERP.Infrastructure.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ElectricERP.Infrastructure.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ElectricERP.Infrastructure.Entities.Almacen", b =>
                {
                    b.Navigation("Secciones");

                    b.Navigation("TransferenciaIdAlmacenDestinoNavigations");

                    b.Navigation("TransferenciaIdAlmacenOrigenNavigations");
                });

            modelBuilder.Entity("ElectricERP.Infrastructure.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Movimientos");

                    b.Navigation("SolicitudAjusteIdEmpleadoSolicitanteNavigations");

                    b.Navigation("SolicitudAjusteIdSupervisorResolutorNavigations");

                    b.Navigation("TransferenciaIdAdministradorAutorizadorNavigations");

                    b.Navigation("TransferenciaIdSupervisorSolicitanteNavigations");

                    b.Navigation("TransferenciaIdTransportistaNavigations");

                    b.Navigation("UbicacionGps");
                });

            modelBuilder.Entity("ElectricERP.Infrastructure.Entities.Inventario", b =>
                {
                    b.Navigation("DetalleInventarios");
                });

            modelBuilder.Entity("ElectricERP.Infrastructure.Entities.Producto", b =>
                {
                    b.Navigation("DetalleInventarios");

                    b.Navigation("DetalleTransferencia");

                    b.Navigation("Etiqueta");

                    b.Navigation("Movimientos");

                    b.Navigation("SolicitudAjustes");

                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("ElectricERP.Infrastructure.Entities.Proveedor", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("ElectricERP.Infrastructure.Entities.Seccion", b =>
                {
                    b.Navigation("Inventarios");

                    b.Navigation("Movimientos");

                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("ElectricERP.Infrastructure.Entities.Stock", b =>
                {
                    b.Navigation("Alerta");
                });

            modelBuilder.Entity("ElectricERP.Infrastructure.Entities.Transferencia", b =>
                {
                    b.Navigation("DetalleTransferencia");
                });

            modelBuilder.Entity("ElectricERP.Infrastructure.Entities.Vehiculo", b =>
                {
                    b.Navigation("Transferencia");
                });
#pragma warning restore 612, 618
        }
    }
}
